import assert from 'node:assert/strict';
import test from 'node:test';
import {
  DRAG_THRESHOLD_PX,
  hasExceededDragThreshold,
  shouldPreventCircleLinkClick,
} from '../src/utils/interaction.js';

test('locked circles always allow link activation', () => {
  assert.equal(shouldPreventCircleLinkClick('locked', false), false);
  assert.equal(shouldPreventCircleLinkClick('locked', true), false);
});

test('editable circles block only the click generated by an actual drag', () => {
  assert.equal(shouldPreventCircleLinkClick('editable', false), false);
  assert.equal(shouldPreventCircleLinkClick('editable', true), true);
});

test('pointer movement below the drag threshold remains a click', () => {
  assert.equal(hasExceededDragThreshold(10, 10, 13, 14), false);
});

test('pointer movement activates dragging at the six pixel threshold', () => {
  assert.equal(DRAG_THRESHOLD_PX, 6);
  assert.equal(hasExceededDragThreshold(10, 10, 16, 10), true);
  assert.equal(hasExceededDragThreshold(10, 10, 6, 14.5), true);
});

test('invalid pointer coordinates cannot activate dragging', () => {
  assert.equal(hasExceededDragThreshold(0, 0, Number.NaN, 10), false);
  assert.equal(hasExceededDragThreshold(0, 0, 10, 10, -1), false);
});
