import assert from 'node:assert/strict';
import test from 'node:test';
import { shouldPreventCircleLinkClick } from '../src/utils/interaction.js';

test('locked circles always allow link activation', () => {
  assert.equal(shouldPreventCircleLinkClick('locked', false), false);
  assert.equal(shouldPreventCircleLinkClick('locked', true), false);
});

test('editable circles block only the click generated by an actual drag', () => {
  assert.equal(shouldPreventCircleLinkClick('editable', false), false);
  assert.equal(shouldPreventCircleLinkClick('editable', true), true);
});
